using AkisaAi.Api.Models;

namespace AkisaAi.Api.Services;

public sealed class ModelRouterService
{
    private readonly OpenAiService _openAiService;
    private readonly ILogger<ModelRouterService> _logger;

    public ModelRouterService(OpenAiService openAiService, ILogger<ModelRouterService> logger)
    {
        _openAiService = openAiService;
        _logger = logger;
    }

    public async Task<string> RouteChatAsync(string prompt, IReadOnlyList<MemoryEntry> memory, IReadOnlyList<ConversationMessage> conversation)
    {
        var contextSummary = BuildContextSummary(memory, conversation);
        var routedPrompt = $"{contextSummary}\n\nUser request: {prompt}";

        if (_openAiService.IsConfigured)
        {
            _logger.LogInformation("Routing chat request to OpenAI provider.");
            try
            {
                return await _openAiService.CreateChatCompletionAsync(routedPrompt);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "OpenAI request failed, falling back to local reasoning.");
            }
        }

        _logger.LogInformation("Using local reasoning fallback.");
        return GenerateLocalResponse(routedPrompt);
    }

    private static string BuildContextSummary(IReadOnlyList<MemoryEntry> memory, IReadOnlyList<ConversationMessage> conversation)
    {
        var memorySection = memory.Any()
            ? string.Join("\n", memory.Take(5).Select(entry => $"* {entry.Type}: {entry.Content}"))
            : "No recent memory available.";

        var conversationSection = conversation.Any()
            ? string.Join("\n", conversation.Skip(Math.Max(0, conversation.Count - 4)).Select(message => $"[{message.Role}] {message.Text}"))
            : "No conversation history available.";

        return $"Memory context:\n{memorySection}\n\nRecent conversation:\n{conversationSection}";
    }

    private static string GenerateLocalResponse(string prompt)
    {
        return $"AKISA-AI local reasoning fallback processed your prompt:\n\n{prompt}\n\nThis response is generated by the local AKISA system. For richer reasoning, configure the OpenAI provider in `OpenAI:ApiKey`.";
    }
}
